[package]
name = "cg"
version = "0.1.0"
authors = ["ding"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
cranelift-codegen = { version = "0.29", default-features = false, features = ["core"] }
